EXPECTED_DIR = "csv_database_collections"

SCHEMA_WHITELIST = {
    "users": {
        "email",
        "membership_start_datetime",
        "is_member",
        "region",
        "accumulated_usages",
        "new_member_promo_code",
        "account_close_reason",
        "date_membership_cancelled",
        "requested_user_data_deletion",
        "is_pilot_participant",
        "internal_testing",
        "cafe_dashboard_admin",
        "id",
        "created",
        "updated",
    },
    "sites": {
        "name",
        "state",
        "city",
        "street_address",
        "return_enabled",
        "borrowing_enabled",
        "return_code",
        "show_on_map_list",
        "zip",
        "borrow_code",
        "region",
        "single_use_surcharge",
        "id",
        "created",
        "updated",
    },
    "region": {
        "name",
        "enable_on_map",
        "map_display_order",
        "id",
        "created",
        "updated",
    },
    "promo_code": {
        "code",
        "promo_type",
        "dollar_off",
        "promo_end",
        "promo_start",
        "max_count",
        "isactive",
        "id",
        "created",
        "updated",
    },
    "user_history": {
        "txn_id",
        "action",
        "user",
        "site",
        "count",
        "manually_scanned",
        "flow",
        "usercontainercount",
        "cups_allowed",
        "original_date_borrowed",
        "id",
        "created",
        "updated",
    },
    "user_payment_history": {
        "date",
        "txn_id",
        "user",
        "reason",
        "dollar_off_applied",
        "pct_off_applied",
        "amount",
        "promo_code",
        "id",
        "created",
        "updated",
    },
    "containers_out": {
        "due",
        "user",
        "mark_for_return",
        "usercontainercount",
        "user_history",
        "returned",
        "borrowed_from_site",
        "1st_reminder_notification_date",
        "2nd_reminder_notification_date",
        "id",
        "created",
        "updated",
    },
}

TABLE_TYPES = {
    "users": "state",
    "containers_out": "state",
    "sites": "state",
    "region": "state",
    "promo_code": "state",
    "user_history": "history",
    "user_payment_history": "history",
}